# Generated by Django 3.0.6 on 2020-06-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comment_multi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='multi',
        ),
    ]
