# Generated by Django 3.0.6 on 2020-06-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200613_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_users',
        ),
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
