# Generated by Django 3.0.6 on 2020-06-11 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multiphoto', '0002_auto_20200611_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiphoto',
            name='like_count',
        ),
        migrations.AddField(
            model_name='multiphoto',
            name='like_users',
            field=models.ManyToManyField(related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
