# Generated by Django 3.0.6 on 2020-06-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiphoto', '0005_auto_20200613_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
