# Generated by Django 3.0.6 on 2020-06-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiphoto', '0006_auto_20200613_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiphoto',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
