# Generated by Django 3.0.6 on 2020-06-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiphoto', '0007_auto_20200613_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiphoto',
            name='like_users',
        ),
        migrations.AddField(
            model_name='multiphoto',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
