# Generated by Django 3.0.6 on 2020-06-13 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiphoto', '0008_auto_20200613_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiphoto',
            name='like_count',
        ),
    ]
